project:
  type: website
  render:
    - 404.qmd
    - index.qmd
    - introduction.qmd
    - general/*.qmd
    - part-01/*.qmd
    - part-02/*.qmd
    - part-03/*.qmd
website:
  title: "Optimization with Julia"
  repo-url: https://github.com/beyondsimulations/Optimization-with-Julia
  site-url: https://beyondsimulations.github.io/Optimization-with-Julia
  bread-crumbs: true
  sidebar:
    style: floating
    logo: https://images.beyondsimulations.com/lectures/mj-hall.png
    collapse-level: 2
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Introduction"
        href: introduction.qmd
      - section: "I. First Steps"
        contents:
          - text: "01 - Variables"
            href: part-01/tutorial-01-01-variables.qmd
          - text: "02 - Vectors"
            href: part-01/tutorial-01-02-vectors.qmd
          - text: "03 - Comparisons"
            href: part-01/tutorial-01-03-comparisons.qmd
          - text: "04 - Loops"
            href: part-01/tutorial-01-04-loops.qmd
          - text: "05 - Dictionaries"
            href: part-01/tutorial-01-05-dicts.qmd
      - section: "II. Data"
        contents:
          - text: "01 - Functions"
            href: part-02/tutorial-02-01-functions.qmd
          - text: "02 - Packages"
            href: part-02/tutorial-02-02-handling.qmd
          - text: "03 - DataFrames"
            href: part-02/tutorial-02-03-DataFrames.qmd
          - text: "04 - Input and Output"
            href: part-02/tutorial-02-04-IO.qmd
          - text: "05 - Plotting"
            href: part-02/tutorial-02-05-Plotting.qmd
      - section: "III. Optimization"
        contents:
          - text: "01 - JuMP"
            href: part-03/tutorial-03-01-jump.qmd
          - text: "02 - Bounds"
            href: part-03/tutorial-03-02-bounds.qmd
          - text: "03 - Constraints"
            href: part-03/tutorial-03-03-constraints.qmd
          - text: "04 - Advanced"
            href: part-03/tutorial-03-04-advanced.qmd
          - text: "05 - Transport"
            href: part-03/tutorial-03-05-transport.qmd
      - section: "Cheatsheets"
        contents:
          - text: "Julia"
            href: general/cheatsheet-julia.qmd
          - text: "JuMP"
            href: general/cheatsheet-jump.qmd
      - text: "Literature"
        href: general/literature.qmd

  page-footer:
    center: "Mathematical Optimization with Julia, Tobias Vlćek</br>CC BY-SA 4.0"
    right:
      - icon: github
        href: https://github.com/beyondsimulations/Optimization-with-Julia
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek

format:
  html:
    theme: [litera, styles.scss]
    toc: true
    highlight-style: arrow
    linkcolor: "#a60000"
    code-copy: true
    code-link: true
    toc-location: right
    code-overflow: wrap
    code-block-bg: true
    code-block-border-left: "#AD1F00"
    include-in-header:
      - general/header.html
    include-after-body:
      text: |
        <script src="https://cdn.jsdelivr.net/gh/beyondsimulations/web-embedded-chat@main/floating-chat.js"></script>
        <script>
            new UniversalChatWidget({
                title: "Julia Assistant",
                apiEndpoint: "https://model-proxy.vlcek-4b4.workers.dev/api",
                model: "julia-programming",
                userMessageOpacity: 0.5,
                assistantMessageOpacity: 0.5,
                position: "bottom-right",
                windowHeight: 800
            });
        </script>

  pdf:
    documentclass: report
    geometry:
      - margin=1in
    fontfamily: roboto
    fontfamilyoptions: sfdefault
    colorlinks: true
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
execute:
  freeze: auto

engine: julia
